# Generated by Django 5.2.7 on 2025-10-29 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
