# Generated by Django 5.2.7 on 2025-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_assigned_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('faculty', 'Faculty Only'), ('admin', 'Admins Only')], default='all', max_length=20),
        ),
    ]
